import type { FaqCategory, FaqItem } from '../types/dudas.types';

export const DUDAS_CATS: FaqCategory[] = [
  'Mas comunes',
  'Cuenta',
  'Constancias',
  'Nomina',
  'Tramites',
  'Soporte',
];

export const DUDAS_FAQS: FaqItem[] = [
  {
    id: 'f1',
    q: 'Que hago si olvide mi contrasena?',
    a: 'Usa la opcion "Recuperar contrasena". Te llegara un codigo al correo registrado para restablecer el acceso.',
    category: 'Mas comunes',
    keywords: ['contrasena', 'recuperacion', 'acceso', 'correo', 'token'],
    guide: { label: 'Guia: Recuperacion de contrasena', href: '/docs/guia-recuperacion.pdf' },
    eta: '3-5 minutos',
    docs: ['Correo institucional o registrado'],
  },
  {
    id: 'f2',
    q: 'No me llega el correo de verificacion, que hago?',
    a: 'Revisa Spam o No deseado, confirma que tu correo este bien escrito y vuelve a solicitar el envio. Si persiste, usa "Soporte".',
    category: 'Cuenta',
    keywords: ['correo', 'verificacion', 'token', 'spam'],
    guide: { label: 'Manual: Acceso y validacion de correo', href: '/docs/manual-acceso.pdf' },
    eta: '2-4 minutos',
    docs: ['Correo correcto', 'Acceso a bandeja de entrada'],
  },
  {
    id: 'f3',
    q: 'Por que no aparece mi constancia para descargar?',
    a: 'Puede deberse a que aun no esta disponible para tu periodo o falta concluir el proceso. Verifica filtros, periodo y estatus.',
    category: 'Constancias',
    keywords: ['constancia', 'descarga', 'periodo', 'estatus'],
    guide: { label: 'Guia: Descarga de constancias', href: '/docs/guia-constancias.pdf' },
    eta: '5-10 minutos',
    docs: ['Periodo correcto', 'Datos actualizados'],
  },
  {
    id: 'f4',
    q: 'Mi PDF se descarga vacio o no abre, que hago?',
    a: 'Intenta con otro navegador, actualiza el lector PDF o vuelve a descargar. Si el archivo sigue vacio, repite el proceso de generacion.',
    category: 'Constancias',
    keywords: ['pdf', 'vacio', 'descarga', 'abre'],
    guide: { label: 'Solucion: Problemas con PDFs', href: '/docs/solucion-pdf.pdf' },
    eta: '3-8 minutos',
    docs: ['Navegador actualizado', 'Lector PDF'],
  },
  {
    id: 'f5',
    q: 'Como descargo recibos de nomina de meses anteriores?',
    a: 'En Nomina, selecciona el periodo deseado y descarga el recibo. Si no aparece, puede ser por vigencia o disponibilidad del sistema.',
    category: 'Nomina',
    keywords: ['nomina', 'recibo', 'periodo', 'meses anteriores'],
    guide: { label: 'Manual: Consulta de recibos de nomina', href: '/docs/manual-recibos-nomina.pdf' },
    eta: '4-6 minutos',
    docs: ['Periodo o mes a consultar'],
  },
  {
    id: 'f6',
    q: 'Puedo corregir datos despues de enviar un tramite?',
    a: 'Depende del proceso. Algunos permiten correccion antes de "Enviar", otros requieren levantar una solicitud de ajuste con soporte.',
    category: 'Tramites',
    keywords: ['corregir', 'datos', 'tramite', 'editar'],
    guide: { label: 'Guia: Correcciones y ajustes', href: '/docs/guia-ajustes.pdf' },
    eta: '5-15 minutos',
    docs: ['Identificacion del tramite', 'Datos correctos'],
  },
  {
    id: 'f7',
    q: 'Que hago si el sistema marca error al enviar?',
    a: 'Revisa tu conexion, valida campos obligatorios y reintenta. Si continua, guarda captura y reportalo a soporte con fecha y hora.',
    category: 'Soporte',
    keywords: ['error', 'enviar', 'fallo', 'soporte'],
    guide: { label: 'Directorio de apoyo tecnico', href: 'https://example.com/soporte' },
    eta: '2-10 minutos',
    docs: ['Captura del error', 'Hora y modulo'],
  },
];
