import type { DocItem } from './guides.types';

export const GUIDES_DOCS: DocItem[] = [
  {
    id: 'g1',
    title: 'Guia rapida: Recuperacion de contrasena',
    desc: 'Pasos para restablecer tu acceso al portal y validar tu correo.',
    category: 'Tramites',
    kind: 'pdf',
    href: '/docs/guia-recuperacion.pdf',
    updatedAt: '2026-02-10',
    size: '1.1 MB',
    isTop: true,
    isNew: true,
  },
  {
    id: 'g2',
    title: 'Formato: Solicitud de constancia',
    desc: 'Formato oficial para iniciar el tramite de constancia.',
    category: 'Formatos',
    kind: 'doc',
    href: '/docs/formato-constancia.docx',
    updatedAt: '2026-01-25',
    size: '220 KB',
    isTop: true,
  },
  {
    id: 'g3',
    title: 'Manual: Consulta de recibos de nomina',
    desc: 'Como ubicar, descargar y validar tus recibos.',
    category: 'Nomina',
    kind: 'pdf',
    href: '/docs/manual-recibos-nomina.pdf',
    updatedAt: '2026-02-02',
    size: '2.4 MB',
    isNew: true,
  },
  {
    id: 'g4',
    title: 'Lineamientos de prestaciones (resumen)',
    desc: 'Puntos clave, vigencias y consideraciones.',
    category: 'Prestaciones',
    kind: 'pdf',
    href: '/docs/lineamientos-prestaciones.pdf',
    updatedAt: '2025-12-18',
    size: '980 KB',
  },
  {
    id: 'g5',
    title: 'Directorio de apoyo tecnico',
    desc: 'Canales de soporte por area y horarios.',
    category: 'Tecnologia',
    kind: 'link',
    href: 'https://example.com/soporte',
    updatedAt: '2026-02-15',
    isTop: true,
  },
  {
    id: 'g6',
    title: 'Checklist de documentos para credito',
    desc: 'Plantilla para preparar tu expediente.',
    category: 'Creditos',
    kind: 'xls',
    href: '/docs/checklist-credito.xlsx',
    updatedAt: '2026-01-08',
    size: '140 KB',
  },
  {
    id: 'g7',
    title: 'Guia: Descarga de constancias',
    desc: 'Como generar y descargar constancias disponibles.',
    category: 'Constancias',
    kind: 'pdf',
    href: '/docs/guia-constancias.pdf',
    updatedAt: '2026-02-05',
    size: '1.6 MB',
    isTop: true,
  },
];
