export { default as Hero } from './ui/Hero/Hero';
export { default as ServicesSection } from './ui/ServicesSection/ServicesSection';
export { default as ConvocatoriasSection } from './ui/ConvocatoriasSection/ConvocatoriasSection';
export { default as GuidesSection } from './ui/GuidesSection/GuidesSection';
export { default as DudasSection } from './ui/DudasSection/DudasSection';
export { default as AppDownloadSection } from './ui/AppDownloadSection/AppDownloadSection';
export { default as QuickAccessSection } from './ui/QuickAccessSection/QuickAccessSection';
export { default as PortalAssistant } from './ui/PortalAssistant/PortalAssistant';
export { default as SiteFooter } from './ui/SiteFooter/SiteFooter';
